.

#### ** https://datascienceschool.net 에서 공부한 내용을 필기노트로 정리한 자료입니다.

#### 1. 수식이해를 위한 '그리스 문자' 학습

<img src="1.jpg" width="1000" />

#### 2.  수식이해를 위한 '수열의 합과 곱' 학습

합이나 곱을 중첩하여 여러 번 쓰는 경우도 있다. 합과 곱을 중첩하여 쓸 때는 아래와 같이 괄호를 생략할 수 있다. 합이나 곱이 중첩된 경우에는 인덱스가 여러 개가 된다.

<img src="2.jpg" width="1000" />

#### 2. 데이터의 유형

선형대수에서 다루는 데이터는 갯수나 형태에 따라 다르다.

아이리스 데이터를 예를 들어서 공부해보자

In [12]:
# 넘파이 패키지 임포트
import numpy as np
# 맷플롯립 패키지 임포트
import matplotlib.pylab as plt
# 사이킷런 패키지 임포트
from sklearn.datasets import load_iris

# 데이터 로드
iris = load_iris()

# 아이리스 데이터 갯수
len(iris.data)

150

In [11]:
# 아이리스 데이터 셋의 첫번째 데이터부터 10번째 데이터까지만 출력
iris.data[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [10]:
# 아이리스 데이터 피쳐
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
# 아이리스 타겟벨류 
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# 아이리스 타겟 네임
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [3]:
# 첫 번째 꽃의 데이터
iris.data[0, :]

array([5.1, 3.5, 1.4, 0.2])

<img src="3.jpg" width="1000" />

<img src="4.jpg" width="1000" />

#### 3. 특수한 벡터와 행렬

1) 영벡터(zeros-vector) 

모든 원소가 0인  N 차원 벡터

2) 일벡터(ones-vector) 

모든 원소가 1인  N 차원 벡터

3) 정방행렬(square matrix) 

행의 개수와 열의 개수가 같은 행렬

4) 대각행렬(diagonal matrix)

행렬에서 행과 열이 같은 위치를 주 대각(main diagonal) 또는 간단히 대각(diagonal)이라고 하고, 대각위치에 있지 않은 것들은 비대각(off-diagonal)이라고 하는데 이때 모든 비대각 요소가 0인 행렬

주의해야 할 점은 대각행렬이 되려면 비대각성분이 0이기만 하면 되고 대각성분은 0이든 아니든 상관없다. 또한 반드시 정방행렬일 필요도 없다. 

예를 들어 아래와 같은 행렬도 대각행렬이라고 할 수 있다.

\begin{align}
D = 
\begin{bmatrix}
d_{1} & 0 & \cdots & 0 \\
0 & d_{2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & d_{M} \\
0 & 0 & \cdots & 0 \\
0 & 0 & \cdots & 0 \\
0 & 0 & \cdots & 0 \\
\end{bmatrix}
\end{align}

\begin{align}
D \in \mathbf{R}^{N \times M}
\end{align}

5) 항등행렬(identity matrix)

대각행렬 중에서도 모든 대각성분의 값이 1인 대각행렬을 항등행렬이라고 한다. 항등행렬은 보통 알파벳 대문자  I 로 표기

6) 대칭행렬(symmetric matrix)

전치연산을 통해서 얻은 전치행렬과 원래의 행렬이 같으면 대칭행렬이라고 한다. 

정방행렬만 대칭행렬이 될 수 있다.

#### 4. 벡터와 행렬의 연산 연습문제 풀이

연습문제 2.2.1

A,B,C 세 회사의 주식은 각각 100만원, 80만원, 50만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하고자 한다.

1) 주식의 가격과 수량을 각각 p벡터, n벡터로 표시하고 넘파이로 코딩한다.


2) 주식을 매수할 때 필요한 금액을 곱셉으로 표시하고 넘파이 연산으로 그 값을 계산한다.

In [3]:
import numpy as np

## 1) 문제풀이
p = np.array([[100],
              [80],
              [50]])

print(p)

n = np.array([[3],
              [4],
              [5]])

print(n)

## 2) 문제풀이
np.dot(p.T, n)

[[100]
 [ 80]
 [ 50]]
[[3]
 [4]
 [5]]


array([[870]])

연습문제 2.2.2

<img src="5.jpg" width="1000" />

연습문제 2.2.3

다음 코드를 실행하면 MNIST 숫자 이미지 전체 데이터를 모두 벡터로 변환하여 하나의 넘파이 행렬 X를 만든다. 이 행렬을 이용하여 다음 문제를 풀어라.

from sklearn.datasets import load_digits

X = load_digits().data

(1) 내적을 이용하여 첫 번째 이미지와 10번째 이미지의 유사도를 구하라

(2) 내적을 이용하여 모든 이미지의 조합에 대해 유사도를 구하라. 어떻게 구현하는 것이 효율적일까? 

(힌트 : 이 문제는 뒤에서 배울 행렬과 행렬의 곱셈을 이용한다.)

In [7]:
from sklearn.datasets import load_digits

print(load_digits())

X = load_digits().data

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [15]:
## 첫번째 데이터 살펴보기
print(X[1])

[ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
  3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
 16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
  0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]


In [19]:
## 1) 문제
np.dot(X[0].reshape(64, 1).T, X[9].reshape(64,1))[0][0]

2807.0

In [20]:
## 2) 문제
np.dot(X, X.T)

array([[3070., 1866., 2264., ..., 2812., 3006., 2898.],
       [1866., 4209., 3432., ..., 3906., 3083., 3307.],
       [2264., 3432., 4388., ..., 4005., 3063., 3697.],
       ...,
       [2812., 3906., 4005., ..., 5092., 3729., 4598.],
       [3006., 3083., 3063., ..., 3729., 4316., 3850.],
       [2898., 3307., 3697., ..., 4598., 3850., 4938.]])

연습문제 2.2.5

다음 코드를 실행하면 붓꽃 전체 데이터를 모두 벡터로 변환하여 하나의 넘파이 행렬 X 를 만든다.

from sklearn.datasets import load_iris
X = load_iris().data

이 데이터로 행렬 $\bar{X}$ 의 값을 계산하라. 이 행렬은 첫 번째 열의 값이 모두 같은 값으로 붓꽃의 꽃받침의 길이(sepal length)의 평균이고 두 번째 열의 값이 모두 같은 값으로 붓꽃의 꽃받침의 폭(sepal width)의 평균, 이런 식으로 계산된 행렬이다.

In [21]:
from sklearn.datasets import load_iris

X = load_iris().data
N = X.shape[0]
ones = np.ones(N).reshape(-1,1)

X_bar = np.dot(np.dot(ones, ones.T),X) / N
X_bar[:5]

array([[5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333]])

연습 문제 2.2.6

다음 행렬의 곱셈을 순서를 바꾸어 두 가지 방법으로 해본다.

$ \begin{align}
\begin{bmatrix} 1 & 2 \end{bmatrix} 
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} 
\begin{bmatrix} 5 \\ 6 \end{bmatrix}
\end{align}$